project/portal/urls.py
from django.urls import path
from . import views
from .views import (
#     CustomerListView, 
    CustomerDetailView,
    CustomerCreateView,
#     CustomerUpdateView,
#     CustomerDeleteView,
#     UserCustomerListView, 
)

urlpatterns = [
    # path('media/favicon.jpg', name='favicon')
    path('', views.home, name='portal-home'),
    # path('', CustomerListView.as_view(), name='portal-home'),
    # path('user/<str:username>', UserCustomerListView.as_view(), name='user-customers'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/new/', CustomerCreateView.as_view(), name='customer-create'),
    # path('customer/<int:pk>/update', CustomerUpdateView.as_view(), name='customer-update'),
    # path('customer/<int:pk>/delete', CustomerDeleteView.as_view(), name='customer-delete'),
    # path('customers/', views.customers, name='portal-customers'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'), 
    path('profile/', user_views.profile, name='profile'), 
    path('login/', auth_views.LoginView.as_view(template_name=('user/login.html')), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(template_name=('user/logout.html')), name='logout'), 
    path('password-reset/', 
         auth_views.PasswordResetView.as_view(template_name=('user/password_reset.html')), 
         name='password_reset'), 
    path('password-reset-done/', 
         auth_views.PasswordResetDoneView.as_view(template_name=('user/password_reset_done.html')), 
         name='password_reset_done'), 
    path('password-reset-confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name=('user/password_reset_confirm.html')), 
         name='password_reset_confirm'), 
    path('password-reset-complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name=('user/password_reset_complete.html')), 
         name='password_reset_complete'), 
    path('', include('portal.urls')),
    path('venture/', include('venture.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from portal.utils.states import STATE_CODES
from portal.utils.validations import PHONE_REGEX

import phonenumbers

# from venture.models import Venture


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # Personal info
    username = models.CharField(max_length=32, null=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=128)
    tax_id = models.CharField(max_length=11)
    # Contacts
    email = models.EmailField(default=None, null=True)
    phone_number = models.CharField(validators=[PHONE_REGEX], max_length=17, null=True)
    # Residential info
    street_name = models.CharField(max_length=256, null=True)
    street_number = models.IntegerField(null=True)
    neighborhood = models.CharField(max_length=64, null=True)
    city = models.CharField(max_length=64, null=True)
    state = models.CharField(max_length=2, choices=STATE_CODES, null=True)
    # User
    entrepreneur = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.full_name
    
    def get_absolute_url(self):
        return reverse('customer-detail', kwargs={'pk': self.pk})

    @property
    def full_name(self):
        "Returns the person's full name."
        return f"{self.first_name} {self.last_name}"

    @property
    def formatted_phone_number(self, country="BR"):
        if (self.phone_number):
            return phonenumbers.format_number(
                phonenumbers.parse(self.phone_number, country), 
                phonenumbers.PhoneNumberFormat.NATIONAL
            )
        return None

project/venture/models.py
from django.db import models

from portal.models import Customer
from django.urls import reverse

from portal.utils.states import STATE_CODES


class Building(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128)
    street_name = models.CharField(max_length=256, null=True)
    street_number = models.IntegerField(null=True)
    neighborhood = models.CharField(max_length=64, null=True)
    city = models.CharField(max_length=64, null=True)
    state = models.CharField(max_length=2, choices=STATE_CODES, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def address(self):
        "Returns the person's full name."
        return f"{self.street_name} {self.street_number}"

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('building-detail', kwargs={'pk': self.pk})


class Venture(models.Model):
    id = models.AutoField(primary_key=True)
    building = models.ForeignKey(Building, on_delete=models.CASCADE, verbose_name='Edifício')
    complement = models.CharField(max_length=32, verbose_name='Complemento')
    price = models.FloatField(default=0, verbose_name='Preço')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Cliente')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.building.name} {self.complement}"


    def get_absolute_url(self):
        return reverse('venture-detail', kwargs={'pk': self.pk})

project/portal/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.db.models import Count
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from portal.form import CustomerRegisterForm

from venture.models import Building, Venture

from .models import Customer


def home(request):
    # Users customers
    customers = [customer for customer in 
        Customer.objects.filter(entrepreneur=request.user)]
    # Users ventures
    ventures = Venture.objects.filter(
        customer__in=customers).values('building').annotate(total=Count('building'))
    # Users buildings ventures' count
    buildings_count = [{
        'building': Building.objects.get(pk=venture['building']), 
        'total': venture['total']} 
    for venture in ventures]

    context = {
        'customers': customers,
        'buildings': [building for building in Building.objects.all()],
        'buildings_count': buildings_count,
        'user': request.user,
    }
    return render(request, 'portal/home.html', context=context)


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer

def get_context_data(self, **kwargs):
    context = super(CustomerDetailView, self).get_context_data(**kwargs)
    context['ventures'] = Venture.objects.filter(customer=self.object)
    return context


class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    # fields = ['first_name', 'last_name', 'tax_id']
    form_class = CustomerRegisterForm
    labels = {
        'first_name': 'Nome',
    }  


    def form_valid(self, form):
        form.instance.entrepreneur = self.request.user
        return super().form_valid(form)

project/portal/templates/portal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'portal/css/main.css' %}" />

    <title>Portal de empreendedores</title>
</head>

<body>
    <br>

    <body>
      
      {% include "portal/header.html" %}

        <!-- main -->
        {% if user.is_authenticated %}
          {% block main %}{% endblock %}
        {% endif %}

    
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
</body>

</html>

project/portal/templates/portal/customer_detail.html
{% extends "portal/base.html" %}

{% block main %}
<main role="main" class="container">

  {% include "portal/personal_data_table.html" %}

  {% include "portal/investments_table.html" %}

</main>

{% endblock main %}

project/portal/templates/portal/customer_form.html
{% extends "portal/base.html" %}
{% load crispy_forms_tags %}
{% block main %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Cliente</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock main %}

project/portal/templates/portal/header.html
{% load static %}
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'portal-home' %}">
          <img class="rounded-circle" src="{% static 'portal/img/favicon.jpg' %}"  width="40" height="40" alt="Badge">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'portal-home' %}">Home</a> -->
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Sair</a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Perfil</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Registar</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

project/portal/templates/portal/home.html
{% extends "portal/base.html" %}

{% block main %}
<main role="main" class="container">
  <div class="jumbotron">
    <h1 class="display-6">Bem vindo {{ user.first_name }}!</h1>
  </div>
  <div class="row">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    <!-- md-8 -->
    <div class="col-md-8">
      <div class="content-section">
        <h3 class="d-flex justify-content-between align-items-center">Clientes<a href="{% url 'customer-create' %}"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a></h3>
        <ul class="list-group">
          {% for customer in customers %}
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="{% url 'customer-detail' customer.id %}">{{ customer.full_name }}</a>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <div class="content-section">
        <h3 class="d-flex justify-content-between align-items-center">Investimentos<a href="{% url 'venture-create' %}"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a></h3>
        <ul class="list-group">
          {% for building_count in buildings_count %}
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" id="list-profile-list" data-toggle="list" href="{% url 'building-detail' building_count.building.id %}">{{ building_count.building.name }}<span class="badge badge-primary badge-pill">{{ building_count.total }}</span></a>
          {% endfor %}
        </ul>
      </div>
    </div>
    <!-- Sidebar md-4 -->
    <div class="col-md-4">
      <div class="content-section">
          <ul class="list-group">
            <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Busca</a>
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Estatísticas</a>
            <a class="list-group-item list-group-item-action" id="list-profile-new-customer" data-toggle="list" href="{% url 'building-create' %}" role="tab" aria-controls="profile">Novo Empreendimento</a>
            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Messagens</a>
            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Configurações</a>
          </ul>
      </div>
    </div>
  </div>
</main>


{% endblock main %}

project/portal/templates/portal/investments_table.html
<div class="col-md-6">
  <div class="content-section">
    <h4 class="d-flex justify-content-between align-items-center">Investimentos<a href="{% url 'venture-create' %}"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a></h4>
    <ul class="list-group">
      {% for venture in customer.venture_set.all %}
      <a href="{% url 'venture-detail' venture.id %}" class="list-group-item list-group-item-action">{{ venture }}</a>
      {% endfor %}
    </ul>
  </div>
</div>

project/portal/templates/portal/personal_data_table.html
<div class="content-section col-md-5">
    <h4>Dados pessoais</h4>
    <table class="table" >
    <!-- <thead><tr><th colspan="2" class="text-center" scope="col">Dados pessoais</th></tr></thead> -->
    <tbody>
      <tr><td>Nome</td><td class="text-right">{{ object.full_name|title }}</td></tr>
      <tr><td>CPF</td><td class="text-right">{{ object.tax_id}}</td></tr>
      <!-- {% if object.formatted_phone_number %} -->
      <tr><td>Telefone</td><td class="text-right">{{ object.formatted_phone_number}}</td></tr>
      <!-- {% endif %} -->
    </tbody>
  </table>
</div>